### ISSUE TITLE
Mentioning external projects

### ISSUE THREAD

**Issue by AlessandroZ** [mehulj94/BrainDamage#1]
Hi,
I don't have any problem that you use my code (from lazagne) for your project. However, it would be nice de credits my work mentioning it (on the readme or on the header of the source code). 
Thanks.

**Comment by THELAZYHACKER91** [comment]
Ok

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by mehulj94** [comment]
Hey AlessandroZ,
Sorry for the error. You have done some amazing work in lazagne. I have updated the files to mention your work.

**Comment by AlessandroZ** [comment]
Thank you ! ;)
