### ISSUE TITLE
No Persistance. Doesn't copy itself in startup folder.

### ISSUE THREAD

**Issue by PulkitSingh256** [mehulj94/BrainDamage#4]
As per the screenshot when executing eclipse.py your output is
Hiding files 
Folder hidden
Adding registries
Keys added
Timestanp changed
Etc etc
But mine just shows keys added and listening. That's it 
It only copies AdobePush.py in startup which won't work untill and unless python is installed on the victim.
Pls help

**Comment by DouglasB2310** [comment]
You can use Python silent install mode if the dev doesn't fixes it.

https://stackoverflow.com/questions/34214607/python-2-7-windows-silent-installer-msi-command-line-option-to-set-the-path

**Comment by mehulj94** [comment]
Use Pyinstaller.
