### ISSUE TITLE
Startup function not working

### ISSUE THREAD

**Issue by sieunhando** [mehulj94/BrainDamage#5]
Hi, I'm trying to build your Telegram Backdoor but I have a problem with Startup functions. 
I build to execute file and changed "copied_startup_filename = 'dllhost.exe'" but It not work and always have error.
And the file which send via email don't work when I try to rename it to "CHL.zip"
Please fix that error. Thanks for reading.

**Comment by mehulj94** [comment]
Can you share screenshots and the config.

**Comment by PulkitSingh256** [comment]
The same thing happened to me.
