### ISSUE TITLE
Run on Win10 64bit Error report

### ISSUE THREAD

**Issue by constantinedev** [mehulj94/BrainDamage#7]
The Python 2.7.9 run out error
=========================================================
`Traceback (most recent call last):
  File "C:\Users\user\Downloads\BrainDamage-master\eclipse.py", line 39, in <module>
    from Echoes import Run
  File "C:\Users\user\Downloads\BrainDamage-master\Echoes\Run.py", line 7, in <module>
    import Mozilla
  File "C:\Users\user\Downloads\BrainDamage-master\Echoes\Mozilla.py", line 10, in <module>
    from pyasn1.codec.der import decoder
ImportError: No module named pyasn1.codec.der`

I have take the issues to run on py2.7.9 (32bit)
Am I firefox are too much update or the web browser software make the bug?

**Comment by mehulj94** [comment]
pycrypto==2.6.1
Pillow==3.4.2
pyHook==1.5.1
pyasn1==0.1.9

Install the above requirements

**Comment by constantinedev** [comment]
OK thx I have install all and can run the error has coming 
it will copy the file called "AdobePush.py" to the windows startup location....
the error are coming in the next boot, when i single to run the AdobePush.py in the startup location
it say <line21>"add_to_registry" object can't input file....

And one more things about the bot....
how can we send the msg to the client single?
or any way can control the bot to insert the python file to the victim?

**Comment by mehulj94** [comment]
Copying to windows startup location is a feature for exe. Since AdobePush.py has dependencies it cannot work alone. Either you need to modify it so that it copies all the dependency files also.

**Comment by constantinedev** [comment]
Yes I know but it just can use the single file name "AdobePush.py" 
Can I change the "eclipse.py" to download my single file to the startup location by url?
and also I have the exe and the config file to push to the user.

**Comment by PulkitSingh256** [comment]
RAT-via-Telegram - https://github.com/PulkitSingh256/NR_RAT_BETA
