### ISSUE TITLE
How to open txt.dsotm files?

### ISSUE THREAD

**Issue by MS-Jahan** [mehulj94/BrainDamage#9]
After opening txt.dsotm files sent to email, I have just found some bla bla characters. Is it encoded? How to decode this type of files?

**Comment by mehulj94** [comment]
https://github.com/mehulj94/BrainDamage/blob/master/Breathe/cloak.py

**Comment by MS-Jahan** [comment]
OK. As I don't know coding much, I couldn't figure it out how to do this. After spending about 15 minutes, I have found out a solution. I'm writing this in comment so that other people who use this will be benefited.

1. Create a python script (e.g. decrypt.py) at the root directory where eclipse.py is stored.
2. Copy-paste the code below:
from Breathe import cloak

```
cipher = cloak.Cloaking()
MainText = cipher.deobfs("PATH_TO_FILE")
print MainText
```

Note that, PATH_TO_FILE will be the location of the txt.dsotm file. (e.g. "C:\Users\Jahan\Downloads\info.txt.dsotm").

After that, run the script from CMD & you'll see the main text.
`python decrypt.py`
